version: 0.1.0
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}-{build}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}+{build}'
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
deploy:
  provider: NuGet
  api_key:
    secure: 5WYfieTRWjVbxE3s3OVLBPjn8RGcVGK0uhHJH6dM8K4xCY7ChkWuPh16/QuQpT5s
  skip_symbols: false
  artifact: /.*\.nupkg/
