version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
deploy:
  provider: NuGet
  api_key:
    secure: 5WYfieTRWjVbxE3s3OVLBPjn8RGcVGK0uhHJH6dM8K4xCY7ChkWuPh16/QuQpT5s
  skip_symbols: false
  artifact: /.*\.nupkg/
